package finance_project;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    private static String filepath = "src\\finance_project\\data.json";
    private static JSONParser jsonParser = new JSONParser();
    private static JSONObject record = new JSONObject();
    private static JSONArray userlist = new JSONArray();
    private static JSONObject user = new JSONObject();
    private final String username;
    private String currency;
    private String theme;

    public Dashboard(String username) {
        initComponents();
        this.username = UserSession.currentUsername;  // Set the username
        jLabel5.setText("Welcome, " + username);  // Display the username
        loadSettingsFromFile();
        loadJsonToTable(currency);  // Pass currency to loadJsonToTable method
        applyTheme(theme);  // Apply the selected theme
        applySettings();
    }

    private void loadSettingsFromFile() {
        File file = new File("settings.json");
        if (file.exists()) {
            try {
                JSONParser parser = new JSONParser();
                JSONObject settings = (JSONObject) parser.parse(new FileReader(file));
                String currency = (String) settings.get("currency");
                String theme = (String) settings.get("theme");

                // Store the loaded settings
                this.currency = currency;
                this.theme = theme;
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void applySettings() {
        // Apply the loaded settings
        applyTheme(theme);
    }

    private void applyTheme(String theme) {
        // Apply the selected theme
        if ("Dark".equals(theme)) {
            // Apply dark theme
            jPanel1.setBackground(java.awt.Color.BLACK);
            jLabel1.setForeground(java.awt.Color.WHITE);
            jLabel2.setForeground(java.awt.Color.WHITE);
            jLabel3.setForeground(java.awt.Color.WHITE);
            jLabel4.setForeground(java.awt.Color.WHITE);
        } else {
            // Apply light theme
            jPanel1.setBackground(java.awt.Color.WHITE);
            jLabel1.setForeground(java.awt.Color.BLACK);
            jLabel2.setForeground(java.awt.Color.BLACK);
            jLabel3.setForeground(java.awt.Color.BLACK);
            jLabel4.setForeground(java.awt.Color.BLACK);

        }
    }

    private Dashboard() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void updateSettings(String currency, String theme) {
        this.currency = currency;
        this.theme = theme;
        loadJsonToTable(currency);  // Refresh the table with the new currency
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Add Income");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 463, 100, 37));

        jButton3.setText("Add Goals");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 463, 100, 37));

        jButton4.setText("Settings");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 463, 100, 37));

        jButton5.setText("Add Expense");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 463, 100, 37));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Balance:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 74, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Income:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Expenses:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 463, 100, 37));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Other:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Username", "Date", "Type", "Category", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 100, 701, 351));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jButton6.setText("Delete Account");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 463, -1, 37));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finance_project/tae yan.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 520));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finance_project/tae yan.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 800, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finance_project/tae yan.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, 40, 520));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finance_project/tae yan.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 40, 90));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finance_project/tae yan.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 800, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AddIncome x = new AddIncome();
        x.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Addgoals x = new Addgoals();
        x.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        AddExpense x = new AddExpense();
        x.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Settings x = new Settings();
        x.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Login().setVisible(false);
        this.dispose();
        JOptionPane.showMessageDialog(this, "Logout Successfully");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Delete x = new Delete();
        x.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    public void loadJsonToTable(String currency) {
        String filePath = "src\\finance_project\\data.json";
        double balance = 0.0; // Initialize balance
        double income = 0.0;
        double expenses = 0.0;
        double other = 0.0;

        try (FileReader reader = new FileReader(filePath)) {
            JSONParser jsonParser = new JSONParser();
            JSONObject data = (JSONObject) jsonParser.parse(reader);
            JSONArray users = (JSONArray) data.get("users");

            DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
            model1.setRowCount(0);  // Clear existing rows

            for (Object obj : users) {
                JSONObject user = (JSONObject) obj;
                String username = (String) user.get("username");
                String type = (String) user.get("type");
                String time = (String) user.get("date");
                String category = (String) user.get("category");

                Object amountObj = user.get("amount");
                Double amount = (amountObj == null) ? 0.0 : (amountObj instanceof String) ? Double.parseDouble((String) amountObj) : (Double) amountObj;

                if (type != null) {
                    if (type.equalsIgnoreCase("Income")) {
                        income += amount;
                    } else if (type.equalsIgnoreCase("Expenses")) {
                        expenses += amount;
                    } else {
                        other += amount;
                    }
                }

                // Apply the selected currency format
                String formattedAmount = formatCurrency(amount, currency);
                model1.addRow(new Object[]{username, time, type, category, formattedAmount});
            }

            // Calculate balance
            balance = income + expenses;

            // Update the labels with the formatted totals
            jLabel1.setText("Balance: " + formatCurrency(balance, currency));
            jLabel2.setText("Income: " + formatCurrency(income, currency));
            jLabel3.setText("Expenses: " + formatCurrency(expenses, currency));
            jLabel4.setText("Other: " + formatCurrency(other, currency));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error loading data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String formatCurrency(double amount, String currency) {
        if ("USD".equals(currency)) {
            return "$ " + String.format("%.2f", amount);
        } else if ("PHP".equals(currency)) {
            return "₱ " + String.format("%.2f", amount);
        }
        return String.format("%.2f", amount); // Default
    }

    public static void filecheck() throws IOException, ParseException {
        File file = new File(filepath);

        // ✅ Check if file exists, if not, create an empty JSON structure
        if (!file.exists()) {
            record = new JSONObject();
            userlist = new JSONArray();
            record.put("users", userlist);
            save(); // Save an empty file to avoid errors
        } else {
            FileReader reader = new FileReader(filepath);
            if (reader.ready()) {
                Scanner scan = new Scanner(reader);
                StringBuilder jsonContent = new StringBuilder();

                while (scan.hasNext()) {
                    jsonContent.append(scan.nextLine());
                }
                reader.close();

                if (!jsonContent.toString().isEmpty()) {
                    record = (JSONObject) jsonParser.parse(jsonContent.toString());
                    userlist = (JSONArray) record.get("users");
                } else {
                    record = new JSONObject();
                    userlist = new JSONArray();
                    record.put("users", userlist);
                }
            }
        }
    }

    public static void save() throws IOException {
        FileWriter file = new FileWriter(filepath);
        file.write(record.toJSONString());
        file.close();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
